# Generated by Django 5.1.3 on 2025-06-06 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('products', '0006_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business.business'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='original',
            field=models.ImageField(max_length=255, upload_to='product_images/%Y/%m/'),
        ),
    ]
