# Generated by Django 5.1.3 on 2025-09-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryimage',
            options={'ordering': ['-is_feature', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='categoryimage',
            name='image',
        ),
        migrations.AddField(
            model_name='categoryimage',
            name='original',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='categories/'),
        ),
        migrations.AddConstraint(
            model_name='categoryimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_feature', True)), fields=('category',), name='unique_feature_image_per_category'),
        ),
    ]
