# Generated by Django 5.1.3 on 2025-09-27 20:13

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_categoryimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimage',
            name='original',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.products.models.category_image_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='original',
            field=models.ImageField(max_length=255, upload_to=apps.products.models.product_image_path),
        ),
    ]
