# Generated by Django 5.1.3 on 2025-10-24 17:10

import apps.products.models
import apps.utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_categoryimage_original_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimage',
            name='original',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=apps.utils.storage.CloudImageStorage(), upload_to=apps.products.models.category_image_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='original',
            field=models.ImageField(max_length=255, storage=apps.utils.storage.CloudImageStorage(), upload_to=apps.products.models.product_image_path),
        ),
    ]
