# Generated by Django 5.1.3 on 2026-02-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
        ('orders', '0004_order_customer_email_order_customer_first_name_and_more'),
    ]

    operations = [
    ]
