# Generated by Django 5.1.3 on 2025-09-08 16:50

import apps.marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.AddField(
            model_name='banner',
            name='original',
            field=models.ImageField(blank=True, null=True, upload_to=apps.marketplace.models.banner_image_path),
        ),
    ]
