# Generated by Django 5.1.3 on 2025-10-24 17:10

import apps.marketplace.models
import apps.utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='original',
            field=models.ImageField(blank=True, null=True, storage=apps.utils.storage.CloudImageStorage(), upload_to=apps.marketplace.models.banner_image_path),
        ),
    ]
