# Generated by Django 5.1.3 on 2025-10-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_banner_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsearchindex',
            name='wishlist_count',
            field=models.IntegerField(default=0),
        ),
    ]
