# Generated by Django 5.1.3 on 2025-06-06 03:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('slug', models.SlugField(unique=True)),
                ('business_type', models.CharField(choices=[('fashion', 'Fashion & Clothing'), ('electronics', 'Electronics'), ('agriculture', 'Agriculture & Farm Produce'), ('food', 'Food & Groceries'), ('health', 'Health & Pharmacy'), ('logistics', 'Logistics & Transport Services'), ('enterteinment', 'Enterteinment & Events'), ('manufacture', 'Manufacture & Processing'), ('sme', 'Small/Medium Enterprise'), ('second-hand', 'SecondHand Dealer'), ('others', 'Others')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=225)),
                ('kra_pin', models.CharField(blank=True, max_length=30)),
                ('business_reg_no', models.CharField(blank=True, max_length=30)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.CreateModel(
            name='BusinessReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('orders_complete', models.IntegerField(default=0)),
                ('orders_pending', models.IntegerField(default=0)),
                ('canceled_orders', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('mpesa_code', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='business.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mpesa_till', 'M-Pesa Till'), ('mpesa_paybill', 'M-Pesa Paybill'), ('mpesa_send_money', 'M-Pesa Send Money'), ('airtel_send_money', 'Airtel Send Money'), ('bank_transfer', 'Bank Transfer'), ('card', 'Credit/Debit Card')], max_length=20)),
                ('till_number', models.CharField(blank=True, max_length=20, null=True)),
                ('business_number', models.CharField(blank=True, max_length=25, null=True)),
                ('paybill_account_number', models.CharField(blank=True, max_length=25, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=25, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=70, null=True)),
                ('card_number', models.CharField(blank=True, max_length=30, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='business.business')),
            ],
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['owner'], name='business_bu_owner_i_e66625_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='businessreview',
            unique_together={('user',)},
        ),
    ]
