# Generated by Django 5.1.3 on 2025-06-06 03:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentMethods',
            new_name='PaymentMethod',
        ),
        migrations.AlterModelOptions(
            name='businessreview',
            options={'verbose_name': 'Business Review', 'verbose_name_plural': 'Business Reviews'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Payment Method', 'verbose_name_plural': 'Payment Methods'},
        ),
        migrations.AlterUniqueTogether(
            name='businessreview',
            unique_together={('product', 'user')},
        ),
    ]
