# Generated by Django 5.1.3 on 2025-06-07 05:58

from django.db import migrations
from ..constants import BUSINESS_PERMISSIONS

def create_initial_data(apps, schema_editor):
    BusinessPermission = apps.get_model('business', 'BusinessPermission')
    BusinessRole = apps.get_model('business', 'BusinessRole')
    
    # Create permissions from BUSINESS_PERMISSIONS
    for key, codename in BUSINESS_PERMISSIONS.items():
        name = key.replace('_', ' ').title()
        BusinessPermission.objects.get_or_create(
            codename=codename,
            defaults={'name': name}
        )
    
    # Create default roles
    default_roles = {
        'Administrator': BUSINESS_PERMISSIONS.values(),
        'Manager': [
            BUSINESS_PERMISSIONS['PRODUCT_ADD'],
            BUSINESS_PERMISSIONS['PRODUCT_EDIT'],
            BUSINESS_PERMISSIONS['ORDER_VIEW'],
            BUSINESS_PERMISSIONS['ORDER_PROCESS'],
        ],
        'Staff': [
            BUSINESS_PERMISSIONS['PRODUCT_VIEW'],
            BUSINESS_PERMISSIONS['ORDER_VIEW'],
        ]
    }
    
    for role_name, permissions in default_roles.items():
        role, _ = BusinessRole.objects.get_or_create(
            name=role_name,
            defaults={'is_default': True}
        )
        permission_objects = BusinessPermission.objects.filter(
            codename__in=permissions
        )
        role.permissions.add(*permission_objects)

def reverse_initial_data(apps, schema_editor):
    BusinessRole = apps.get_model('business', 'BusinessRole')
    BusinessPermission = apps.get_model('business', 'BusinessPermission')
    
    BusinessRole.objects.all().delete()
    BusinessPermission.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ('business', '0003_create_business_models'),  # Replace XXXX with actual migration number
    ]
    
    operations = [
        migrations.RunPython(
            create_initial_data,
            reverse_code=reverse_initial_data
        ),
    ]