# Generated by Django 5.1.3 on 2026-02-08 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('orders', '0003_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(db_index=True, help_text='Phone number in international format', max_length=20)),
                ('message', models.TextField(help_text='SMS content sent')),
                ('message_type', models.CharField(choices=[('order_confirmation', 'Order Confirmation'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('seller_new_order', 'Seller New Order'), ('signup_welcome', 'Signup Welcome'), ('password_reset', 'Password Reset'), ('account_verification', 'Account Verification'), ('business_verification', 'Business Verification'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('generic', 'Generic')], db_index=True, default='generic', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('queued', 'Queued')], db_index=True, default='pending', max_length=20)),
                ('at_message_id', models.CharField(blank=True, help_text="Africa's Talking message ID", max_length=100, null=True)),
                ('at_status_code', models.IntegerField(blank=True, help_text='Status code from AT (100=Processed, 101=Sent, 102=Queued)', null=True)),
                ('at_cost', models.CharField(blank=True, help_text='SMS cost', max_length=20, null=True)),
                ('at_response', models.JSONField(blank=True, help_text="Full API response from Africa's Talking", null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if sending failed', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When SMS was successfully sent', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When SMS was delivered (if DLR available)', null=True)),
                ('sender_id', models.CharField(blank=True, help_text='Sender ID used', max_length=20, null=True)),
                ('message_length', models.IntegerField(default=0, help_text='Character count')),
                ('sms_count', models.IntegerField(default=1, help_text='Number of SMS parts (160 chars = 1 SMS)')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'status'], name='notificatio_created_33e7e7_idx'), models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_47715d_idx'), models.Index(fields=['message_type', '-created_at'], name='notificatio_message_12df45_idx')],
            },
        ),
    ]
