# Generated by Django 5.1.3 on 2026-02-08 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_smslog'),
        ('orders', '0006_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(db_index=True, help_text='Email address', max_length=254)),
                ('subject', models.CharField(help_text='Email subject line', max_length=255)),
                ('html_content', models.TextField(help_text='HTML email content')),
                ('text_content', models.TextField(blank=True, help_text='Plain text fallback', null=True)),
                ('email_type', models.CharField(choices=[('order_confirmation', 'Order Confirmation'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('seller_new_order', 'Seller New Order'), ('signup_welcome', 'Signup Welcome'), ('password_reset', 'Password Reset'), ('account_verification', 'Account Verification'), ('business_verification', 'Business Verification'), ('payment_confirmation', 'Payment Confirmation'), ('payment_failed', 'Payment Failed'), ('low_stock_alert', 'Low Stock Alert'), ('review_received', 'Review Received'), ('dispute_opened', 'Dispute Opened'), ('generic', 'Generic')], db_index=True, default='generic', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('complained', 'Complained')], db_index=True, default='pending', max_length=20)),
                ('resend_id', models.CharField(blank=True, help_text='Resend email ID', max_length=100, null=True)),
                ('resend_response', models.JSONField(blank=True, help_text='Full API response from Resend', null=True)),
                ('from_email', models.EmailField(default='noreply@dima.co.ke', help_text='Sender email address', max_length=254)),
                ('from_name', models.CharField(default='Dima Marketplace', help_text='Sender name', max_length=100)),
                ('reply_to', models.EmailField(blank=True, help_text='Reply-to address', max_length=254, null=True)),
                ('cc', models.JSONField(blank=True, help_text='CC recipients list', null=True)),
                ('bcc', models.JSONField(blank=True, help_text='BCC recipients list', null=True)),
                ('attachments', models.JSONField(blank=True, help_text='Attachment metadata', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if sending failed', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When email was successfully sent', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When email was delivered', null=True)),
                ('opened_at', models.DateTimeField(blank=True, help_text='When email was first opened', null=True)),
                ('clicked_at', models.DateTimeField(blank=True, help_text='When links were clicked', null=True)),
                ('opens_count', models.IntegerField(default=0, help_text='Number of times opened')),
                ('clicks_count', models.IntegerField(default=0, help_text='Number of link clicks')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'status'], name='notificatio_created_c85051_idx'), models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_f70bc1_idx'), models.Index(fields=['email_type', '-created_at'], name='notificatio_email_t_e9837a_idx')],
            },
        ),
    ]
